apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: custom-components
  description: Example Custom Components
spec:
  targets:
    - ./components/modiface.yaml
    - ./components/consumer-loop.yaml
